
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: openbao-restic-creds
spec:
  provider: bao
  parameters:
    roleName: "backup"
    baoAddress: "http://openbao:8200"
    objects: |-
      - objectName: aws_access_key_id
        secretPath: "secret/data/backup/restic"
        secretKey: "aws_access_key_id"
      - objectName: aws_secret_access_key
        secretPath: "secret/data/backup/restic"
        secretKey: "aws_secret_access_key"
      - objectName: restic_repository
        secretPath: "secret/data/backup/restic"
        secretKey: "restic_repository"
      - objectName: restic_password
        secretPath: "secret/data/backup/restic"
        secretKey: "restic_password"
      - objectName: bao_token
        secretPath: "secret/data/backup/token"
        secretKey: "value"
  secretObjects:
  - secretName: restic-creds-k8s
    type: Opaque
    data:
    - key: AWS_ACCESS_KEY_ID
      objectName: aws_access_key_id
    - key: AWS_SECRET_ACCESS_KEY
      objectName: aws_secret_access_key
    - key: RESTIC_REPOSITORY
      objectName: restic_repository
    - key: RESTIC_PASSWORD
      objectName: restic_password
    - key: BAO_TOKEN
      objectName: bao_token
