name: Build and Push Multi-Arch Containers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v10

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate lowercase repository owner name
        id: repo_owner
        run: echo "name=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Build and Push openbao-bootstrap-init
        run: |
          nix run .#push-multi-arch -- \
            bootstrap-init \
            openbao-bootstrap-init \
            ${{ steps.repo_owner.outputs.name }}

      - name: Build and Push openbao-unsealer-sidecar
        run: |
          nix run .#push-multi-arch -- \
            unsealer-sidecar \
            openbao-unsealer-sidecar \
            ${{ steps.repo_owner.outputs.name }}

      - name: Build and Push openbao-with-seal-support
        run: |
          nix run .#push-multi-arch -- \
            openbao-main \
            openbao-with-seal-support \
            ${{ steps.repo_owner.outputs.name }}